#!/bin/bash
set -eu

cmd=${1-website}
URL=https://factor-eleven.atlassian.net/

if [[ $cmd == "website" ]]; then
    open $URL
    exit 0
fi

if [[ $cmd =~ ^AM-[0-9]{2,} ]]; then
    open $URL/browse/$cmd
    exit 0
else
    echo no match
fi

echo "noop :)"
