#!/bin/bash

set -eu

# get window ids out by query different spaces
windows=`yabai -m query --spaces | jq '.[] | .windows | join(",")'`

# loop through them 
space_strip=""
declare -i count=0

space_symbols=(🦖 🐘 🐊 四 五 六 七 八 九 十)

for i in $windows; do
    clean=${i//\"/}
    space_strip="$space_strip${space_symbols[$count]}"

    if [[ $clean =~ "," ]]; then
        subwindow_names=""
        for subwindow in ${clean//,/ }; do
            window_name=`yabai -m query --windows --window $subwindow | jq '.app'`
            subwindow_names="$subwindow_names${window_name// /_}/"
        done
        space_strip="$space_strip(${subwindow_names/%\//}) "
    elif [[ -n "$clean" ]]; then
        window_name=`yabai -m query --windows --window $clean | jq '.app'`
        space_strip="$space_strip(${window_name// /_}) "
    else
        space_strip="$space_strip "
    fi;

    count=$(( count + 1 ))
done

str_without_quote=${space_strip//\"/}

# setting the space
yabai -m config status_bar_space_icon_strip $str_without_quote
